$primary = rgb(ccbff4)
$surface = rgb(191429)
$secondary = rgb(e5c3f0)
$error = rgb(fd4663)
$tertiary = rgb(ecc7e3)
$surface_lowest = rgb(0d0a14)

general {
    col.active_border = $primary
    col.inactive_border = $surface
}

group {
    col.border_active = $secondary
    col.border_inactive = $surface
    col.border_locked_active = $error
    col.border_locked_inactive = $surface

    groupbar {
        col.active = $secondary
        col.inactive = $surface
        col.locked_active = $error
        col.locked_inactive = $surface
    }
}
